/*
 * JSMin
 * Javascript Compressor
 * http://www.crockford.com/
 * http://www.smallsharptools.com/Projects/Packer/
*/

// Source\sympleTech_Ajax.js

$.fn.sympleTech_ajaxlink=function(options){var settings=$.extend({'httpMethod':'GET','showHideLoaderMethod':function(show){},'onComplete':function(data){}},options);return this.each(function(){var href=$(this).attr('href');$(this).click(function(e){e.preventDefault();e.stopPropagation();settings.showHideLoaderMethod(true);$.ajax({url:href,type:settings.httpMethod,success:function(data){settings.onComplete(data);settings.showHideLoaderMethod(false);}});});});};$.fn.sympleTech_ajaxform=function(options){var settings=$.extend({'showHideLoaderMethod':function(show){},'requiredFields':[],'requiredFieldClass':'field-required','errorMessageTarget':'','fieldErrorClass':'field-error','beforeSubmit':function(valState){},'action':$(this).attr("action"),'onComplete':function(data){}},options);var validationState={isValid:true,errorMessage:''};var checkRequiredFields=function(form){for(var i in settings.requiredFields){var rField=$(form).find('*[name="'+settings.requiredFields[i]+'"]');if($(rField).val()==""){validationState.errorMessage+="<li>"+$(rField).attr("name")+" is Required</li>";$(rField).addClass(settings.fieldErrorClass);validationState.isValid=false;}else{$(rField).removeClass(settings.fieldErrorClass);}}};return this.each(function(){for(var i=0;i<settings.requiredFields.length;i++){$(this).find('*[name="'+settings.requiredFields[i]+'"]').addClass(settings.requiredFieldClass);}
$(this).submit(function(e){e.preventDefault();settings.showHideLoaderMethod(true);settings.beforeSubmit(validationState);checkRequiredFields(this);if(validationState.isValid){$.post(settings.action,$(this).serialize(),function(data){settings.onComplete(data);settings.showHideLoaderMethod(false);});}else{$(settings.errorMessageTarget).html(validationState.errorMessage);settings.showHideLoaderMethod(false);}});});};
// Source\sympleTech_helpers.js

$.fn.disable=function(){return $(this).each(function(){$(this).attr('disabled','disabled');});};$.fn.enable=function(){return $(this).each(function(){$(this).removeAttr('disabled');});};
// Source\sympleTech_KendoGrid.js

$.fn.sympleTech_KendoGrid=function(options){var settings=$.extend({'title':'','dataSourceURL':'','exportName':'GridData','model':{id:'id',fields:{}},'columns':[],'pagesize':10,'rowSelectable':false,'onRowSelected':function(id){},'multiSelectable':false,'searchForm':'','showExport':false,'height':null,'dataBound':function(e){}},options);return this.each(function(){var formParams={};if(settings.searchForm!=""){var $form=$("#"+settings.searchForm);var formData=$form.serialize().split('&');$(formData).each(function(){var nvp=this.split('=');formParams[nvp[0]]=function(){var $inputEl=$form.find('*[name='+nvp[0]+']').first();if($inputEl.attr("type")=="checkbox"){return $inputEl.is(':checked');}
return $inputEl.val();};});}
var gridDataSource=new kendo.data.DataSource({transport:{read:{url:settings.dataSourceURL,type:"POST",data:formParams}},schema:{data:function(data){return data.Items;},model:settings.model,total:function(data){return data.TotalCount;}},serverSorting:true,serverPaging:true,pageSize:settings.pagesize});var pageSizeChoices=[5,10,15];if($.inArray(settings.pagesize,pageSizeChoices)==-1){pageSizeChoices.push(settings.pagesize);pageSizeChoices.sort(function(a,b){return a-b});}
var titleBar='<div class="grid-title" style="min-height:20px;">';if(settings.showExport==true){var exportUrl=settings.dataSourceURL;if(exportUrl.indexOf('?')>-1){exportUrl+="&";}else{exportUrl+="?";}
exportUrl+="export="+settings.exportName;var exportAnchor="<a href='"+exportUrl+"' target='_blank'>Export</a>";titleBar+='<div style="float:right">'+exportAnchor+"</div>";}
titleBar+='<b>'+settings.title+'</b>';titleBar+='</div>';if(settings.multiSelectable===true){settings.columns.splice(1,0,{field:"check_row",title:" ",width:30,template:"<input class='check_row' type='checkbox' />"});}
var $this=$(this);var grid=$this.kendoGrid({dataSource:gridDataSource,pageable:{refresh:true,pageSize:settings.pagesize,pageSizes:pageSizeChoices},sortable:true,resizable:true,height:settings.height,selectable:(settings.rowSelectable===true)?"row":"",change:function(arg){var selected=$.map(this.select(),function(item){return $(item).find('td').first().text();});$this.attr('data-sympleTech-KendoGrid-selected',selected[0]);settings.onRowSelected(selected[0]);},toolbar:titleBar,columns:settings.columns,dataBound:function(e){$this.find(".k-grid-header colgroup col").first().hide();$this.find(".k-grid-content colgroup col").first().hide();$this.find("thead th").first().hide();$this.find(".k-grid-content tbody tr").each(function(){var $hiddenCell=$(this).find('td').first();$hiddenCell.hide();$hiddenCell.parent('tr').addClass('kendo-data-row').attr("data-sympleTech-KendoGrid-rowid",$hiddenCell.text());if(settings.rowSelectable==true){$(this).addClass('hoverable');}});$this.find(".k-grid-content tbody tr td").each(function(){if($(this).html()=="null"){$(this).html("");}});var selectedRowIds=$this.attr('data-sympleTech-KendoGrid-selected');if(selectedRowIds!=null){var selectedRowIdArray=selectedRowIds.split(',');var visibleRows=$this.find('.kendo-data-row');$(visibleRows).each(function(){var rowID=$(this).attr('data-sympleTech-KendoGrid-rowid');if(_.contains(selectedRowIdArray,rowID)){$(this).addClass('k-state-selected');$(this).find('.check_row').attr('checked','checked');}});}
settings.dataBound(e);}});var gData=grid.data("kendoGrid");if(settings.searchForm!=""){$("#"+settings.searchForm).submit(function(e){e.preventDefault();gData.dataSource.read();});}
if(settings.multiSelectable===true){$('.check_row').live('click',function(e){gData.tbody.find('tr').removeClass('k-state-selected');var checkedBoxes=gData.tbody.find(".check_row:checked");var selectedVals=[];$(checkedBoxes).each(function(){var selectedRow=$(this).parents("tr:first");selectedRow.addClass('k-state-selected');var rowID=$(selectedRow).find('td:first').text();selectedVals.push(rowID);});grid.attr('data-sympleTech-KendoGrid-selected',selectedVals);settings.onRowSelected(selectedVals);});}
return grid;});};
